import 'package:cardwave/character/character.dart';
import 'package:cardwave/main.dart' as app;
import 'package:cardwave/settings/settings.dart';
import 'package:cardwave_llm/cardwave_llm.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:provider/provider.dart';

import 'app_test_helpers.dart';

/// Auto-tag end-to-end via the grid card's popupmenu. Drives the same
/// path a user takes: open the seed character's `more_vert` menu, tap Auto-Tag, wait
/// for the structured-output Grok call to round-trip, verify the seed character's
/// `appCardTags` got populated with valid taxonomy IDs and the legacy
/// `card.tags` list is in sync.
///
/// Verifies in one shot that (a) the system-domain picker auto-assigns
/// a structured-output model after `seedGrokRecovery`, (b) the schema
/// generated by `TaxonomyRepository.buildAutoTagSchema` is one Grok
/// accepts, and (c) the response flatten + sink path lands cleanly.
/// One Grok system-domain LLM call.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets(
    'Grid — Auto-Tag from seed card popupmenu populates tags',
    timeout: const Timeout(Duration(minutes: 3)),
    (tester) async {
      if (!hasGrokKey) {
        markTestSkipped('GROK_API_KEY not supplied (pass --dart-define).');
        return;
      }

      await wipeAppData();
      await seedTestCharacter();
      await seedGrokRecovery();

      app.main();
      await awaitAppReady(tester);
      await awaitGridReady(tester);

      final appCtx = tester.element(find.byType(MaterialApp));
      final characterService = appCtx.read<CharacterService>();
      final characterAiService = appCtx.read<CharacterAiService>();
      final taxonomyRepository = appCtx.read<TaxonomyRepository>();
      final pureHelpers = appCtx.read<LlmPureHelpers>();
      final settingsService = appCtx.read<SettingsService>();

      final seedFile = (await characterService.loadByName(kSeedCharacterName))!;
      final seedPath = seedFile.appCardImagePath;

      // Pre-flight: the system preset must be assigned to a structured-output
      // model. If `_resolveModelForDomain` finds no qualifying Grok model,
      // `_seedDefaultDomainPresetsIfEmpty` skips the system slot and the
      // auto-tag call would later die with a confusing missing-preset error
      // pointing at the wrong layer. Catching it here names the layer.
      final presetId = settingsService.settings.getAppDomainPresetId(
        LlmProviderDomainEnum.system,
      );
      expect(
        presetId,
        isNotNull,
        reason:
            'system preset should be auto-assigned after Grok seed; '
            'a null id means no Grok model qualifies — regression in the '
            'system-domain picker filter or Grok parseModel.',
      );
      final resolved = pureHelpers.resolvePreset(
        configId: presetId!,
        providers: settingsService.settings.providerConfigs,
      );
      expect(
        resolved.model.capabilities.structuredOutput,
        isTrue,
        reason:
            'system-domain model "${resolved.model.id}" lacks '
            'structuredOutput; the picker filter is broken or Grok parseModel '
            'stopped tagging this model.',
      );

      // Open the seed character's popupmenu and tap Auto-Tag. Same descendant pattern as
      // character_delete_test.dart — only the seed character on the grid, so
      // neither the more_vert finder nor the 'Auto-Tag' label is ambiguous.
      final seedMore = find.descendant(
        of: findCharacterTile(kSeedCharacterName),
        matching: find.byIcon(Icons.more_vert),
      );
      await tester.tap(seedMore);
      await tester.pumpAndSettle();
      await tester.tap(find.byKey(const Key('drawer-ai-action-autoTag')));
      await tester.pumpAndSettle();

      // Wait for the in-flight Grok call to finish. `pumpAndSettle` doesn't
      // wait for HTTP — poll the per-task flag the grid overlay reads.
      final deadline = DateTime.now().add(const Duration(seconds: 90));
      while (DateTime.now().isBefore(deadline)) {
        await tester.pump(const Duration(milliseconds: 500));
        if (!characterAiService.isProcessingAiTask(seedPath)) {
          await tester.pumpAndSettle(const Duration(milliseconds: 200));
          break;
        }
      }
      expect(
        characterAiService.isProcessingAiTask(seedPath),
        isFalse,
        reason:
            'auto-tag did not finish for $seedPath within 90s — '
            'check Grok reachability and the structured-output schema.',
      );

      expect(
        seedFile.appCardTags,
        isNotEmpty,
        reason:
            'auto-tagger returned no tag IDs for the seed card; the structured '
            'response was empty or _flattenAutoTagResponse dropped values.',
      );
      expect(
        seedFile.appCardTags.length,
        lessThanOrEqualTo(10),
        reason:
            'auto-tagger returned >10 tag IDs (prompt caps at 10) — '
            'either the model ignored the cap or the flatten leaked dupes.',
      );
      for (final tagId in seedFile.appCardTags) {
        expect(
          taxonomyRepository.getTag(tagId),
          isNotNull,
          reason:
              'auto-tag returned unknown tag id "$tagId" — schema enum '
              'drift or response parsing leaked a non-tag value.',
        );
      }
      expect(
        seedFile.card.tags,
        isNotEmpty,
        reason:
            'card.tags (legacy SillyTavern display list) should hold '
            'the resolved names for every newly-assigned appCardTag.',
      );
      for (final tagId in seedFile.appCardTags) {
        final tagName = taxonomyRepository.getTag(tagId)!.tagName;
        expect(
          seedFile.card.tags.any(
            (existing) => existing.toLowerCase() == tagName.toLowerCase(),
          ),
          isTrue,
          reason: 'tag id "$tagId" → name "$tagName" missing from card.tags.',
        );
      }
    },
  );
}
