// Phase 3 of the name-database build. Reads the tagged JSON and emits a
// Dart source file with two const top-level lists the cardwave_names
// package compiles in directly — no runtime asset loading, no JSON
// parse at startup.
//
// Run from app/ via:
//   dart run tools/generate_names/emit_dart.dart
//
// Output: packages/cardwave_names/lib/src/services/name_database_data.dart
//
// Deterministic: re-running on the same tagged JSON produces a
// byte-identical Dart file.

import 'dart:convert';
import 'dart:io';

import 'loaders/local_taxonomy.dart';

const _inputPath = 'tools/generate_names/data/name_database.tagged.json';
const _outputPath =
    'packages/cardwave_names/lib/src/services/name_database_data.dart';

Future<void> main() async {
  final raw = File(_inputPath).readAsStringSync();
  final root = jsonDecode(raw) as Map<String, dynamic>;
  final firsts = (root['first_names'] as List).cast<Map<String, dynamic>>();
  final lasts = (root['last_names'] as List).cast<Map<String, dynamic>>();

  final buf = StringBuffer();
  buf.writeln('// AUTO-GENERATED by tools/generate_names/emit_dart.dart');
  buf.writeln('// DO NOT EDIT. Re-run the emitter after classify changes.');
  buf.writeln();
  buf.writeln("import 'package:cardwave_names/src/models/name_entry.dart';");
  buf.writeln(
    "import 'package:cardwave_names/src/models/name_surname.dart';",
  );
  buf.writeln(
    "import 'package:cardwave_names/src/models/name_taxonomy.dart';",
  );
  buf.writeln();
  buf.writeln('const firstNamesData = <NameEntry>[');
  for (final e in firsts) {
    buf.writeln(_emitFirst(e));
  }
  buf.writeln('];');
  buf.writeln();
  buf.writeln('const lastNamesData = <NameSurname>[');
  for (final e in lasts) {
    buf.writeln(_emitLast(e));
  }
  buf.writeln('];');

  File(_outputPath).writeAsStringSync(buf.toString());
  stdout.writeln(
    '[done] wrote ${firsts.length} first + ${lasts.length} last → $_outputPath',
  );
}

String _emitFirst(Map<String, dynamic> e) => [
      '  NameEntry(',
      '    name: ${_quote(e['name'] as String)},',
      '    gender: GenderEnum.${e['gender']},',
      '    languageEthnicity: LanguageEthnicityEnum.${e['language_ethnicity']},',
      if (e['mythology'] != null)
        '    mythology: MythologyEnum.${e['mythology']},',
      '    race: RaceEnum.${e['race']},',
      '    age: ${_emitEnumList(AgeEnum.values, e['age'] as List)},',
      '    era: ${_emitEnumList(EraEnum.values, e['era'] as List)},',
      '    role: ${_emitEnumList(RoleEnum.values, e['role'] as List)},',
      '    intelligence: ${e['intelligence']},',
      '    allure: ${e['allure']},',
      '    commonness: CommonnessEnum.${e['commonness']},',
      '    genre: ${_emitEnumList(GenreEnum.values, e['genre'] as List)},',
      '    themes: ${_emitEnumList(ThemeEnum.values, e['themes'] as List)},',
      '  ),',
    ].join('\n');

String _emitLast(Map<String, dynamic> e) => [
      '  NameSurname(',
      '    name: ${_quote(e['name'] as String)},',
      '    languageEthnicity: LanguageEthnicityEnum.${e['language_ethnicity']},',
      if (e['mythology'] != null)
        '    mythology: MythologyEnum.${e['mythology']},',
      '    race: RaceEnum.${e['race']},',
      '    era: ${_emitEnumList(EraEnum.values, e['era'] as List)},',
      '    commonness: CommonnessEnum.${e['commonness']},',
      '    genre: ${_emitEnumList(GenreEnum.values, e['genre'] as List)},',
      '    themes: ${_emitEnumList(ThemeEnum.values, e['themes'] as List)},',
      '  ),',
    ].join('\n');

/// Emits `<EnumName>[EnumName.a, EnumName.b]`. Drops any JSON string
/// that isn't in [enumValues] — protects the emitted Dart from
/// referencing an enum value that's since been removed.
String _emitEnumList<T extends Enum>(List<T> enumValues, List<dynamic> raw) {
  final valid = enumValues.map((e) => e.name).toSet();
  final filtered = raw.cast<String>().where(valid.contains).toList();
  final enumName = T.toString();
  if (filtered.isEmpty) return '<$enumName>[]';
  final inner = filtered.map((v) => '$enumName.$v').join(', ');
  return '<$enumName>[$inner]';
}

/// Quote a string for inclusion in Dart source. jsonEncode handles
/// double-quote / backslash / control-char escapes; we additionally
/// escape `$` so Dart's string-interpolation parser doesn't misread
/// it. Output is always double-quoted.
String _quote(String s) =>
    jsonEncode(s).replaceAll(r'$', r'\$');
