import 'package:cardwave_llm/src/models/llm_model.dart' show LlmModel;
import 'package:cardwave_llm/src/models/llm_parameter_definition_id_enum.dart';
import 'package:cardwave_llm/src/models/llm_preset_config_reasoning_effort_enum.dart';
import 'package:json_annotation/json_annotation.dart';

part 'llm_preset_config.g.dart';

/// User-defined preset (tuning parameters + reasoning effort) attached to a
/// specific [LlmModel]. The model identity lives on the parent [LlmModel],
/// not here.
@JsonSerializable()
class LlmPresetConfig {
  LlmPresetConfig({
    required this.id,
    required this.name,
    this.parameterValues = const {},
    this.reasoningEffort = LlmPresetConfigReasoningEffortEnum.off,
  });

  factory LlmPresetConfig.fromJson(Map<String, dynamic> json) =>
      _$LlmPresetConfigFromJson(json);

  /// Autogenerated UID
  String id;
  String name;
  @JsonKey(defaultValue: {})
  Map<LlmParameterDefinitionIdEnum, double> parameterValues;
  @JsonKey(
    defaultValue: LlmPresetConfigReasoningEffortEnum.off,
    unknownEnumValue: LlmPresetConfigReasoningEffortEnum.off,
  )
  LlmPresetConfigReasoningEffortEnum reasoningEffort;
  Map<String, dynamic> toJson() => _$LlmPresetConfigToJson(this);
}
