// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'name_entry.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

NameEntry _$NameEntryFromJson(Map<String, dynamic> json) => NameEntry(
  name: json['name'] as String,
  gender: $enumDecode(_$GenderEnumEnumMap, json['gender']),
  languageEthnicity: $enumDecode(
    _$LanguageEthnicityEnumEnumMap,
    json['language_ethnicity'],
  ),
  mythology: $enumDecodeNullable(_$MythologyEnumEnumMap, json['mythology']),
  race: $enumDecode(_$RaceEnumEnumMap, json['race']),
  age: $enumDecode(_$AgeEnumEnumMap, json['age']),
  era: $enumDecode(_$EraEnumEnumMap, json['era']),
  role: $enumDecode(_$RoleEnumEnumMap, json['role']),
  intelligence: (json['intelligence'] as num).toInt(),
  allure: (json['allure'] as num).toInt(),
  commonness: $enumDecode(_$CommonnessEnumEnumMap, json['commonness']),
  genre:
      (json['genre'] as List<dynamic>?)
          ?.map((e) => $enumDecode(_$GenreEnumEnumMap, e))
          .toList() ??
      [],
  themes:
      (json['themes'] as List<dynamic>?)
          ?.map((e) => $enumDecode(_$ThemeEnumEnumMap, e))
          .toList() ??
      [],
);

Map<String, dynamic> _$NameEntryToJson(NameEntry instance) => <String, dynamic>{
  'name': instance.name,
  'gender': _$GenderEnumEnumMap[instance.gender]!,
  'language_ethnicity':
      _$LanguageEthnicityEnumEnumMap[instance.languageEthnicity]!,
  'mythology': _$MythologyEnumEnumMap[instance.mythology],
  'race': _$RaceEnumEnumMap[instance.race]!,
  'age': _$AgeEnumEnumMap[instance.age]!,
  'era': _$EraEnumEnumMap[instance.era]!,
  'role': _$RoleEnumEnumMap[instance.role]!,
  'intelligence': instance.intelligence,
  'allure': instance.allure,
  'commonness': _$CommonnessEnumEnumMap[instance.commonness]!,
  'genre': instance.genre.map((e) => _$GenreEnumEnumMap[e]!).toList(),
  'themes': instance.themes.map((e) => _$ThemeEnumEnumMap[e]!).toList(),
};

const _$GenderEnumEnumMap = {
  GenderEnum.male: 'male',
  GenderEnum.female: 'female',
  GenderEnum.ambiguous: 'ambiguous',
};

const _$LanguageEthnicityEnumEnumMap = {
  LanguageEthnicityEnum.english: 'english',
  LanguageEthnicityEnum.japanese: 'japanese',
  LanguageEthnicityEnum.chinese: 'chinese',
  LanguageEthnicityEnum.korean: 'korean',
  LanguageEthnicityEnum.arabic: 'arabic',
  LanguageEthnicityEnum.hebrew: 'hebrew',
  LanguageEthnicityEnum.slavicRussian: 'slavicRussian',
  LanguageEthnicityEnum.slavicPolish: 'slavicPolish',
  LanguageEthnicityEnum.slavicOther: 'slavicOther',
  LanguageEthnicityEnum.french: 'french',
  LanguageEthnicityEnum.spanish: 'spanish',
  LanguageEthnicityEnum.italian: 'italian',
  LanguageEthnicityEnum.portuguese: 'portuguese',
  LanguageEthnicityEnum.german: 'german',
  LanguageEthnicityEnum.dutch: 'dutch',
  LanguageEthnicityEnum.scandinavian: 'scandinavian',
  LanguageEthnicityEnum.irishGaelic: 'irishGaelic',
  LanguageEthnicityEnum.welsh: 'welsh',
  LanguageEthnicityEnum.scottish: 'scottish',
  LanguageEthnicityEnum.greek: 'greek',
  LanguageEthnicityEnum.latin: 'latin',
  LanguageEthnicityEnum.hindi: 'hindi',
  LanguageEthnicityEnum.persian: 'persian',
  LanguageEthnicityEnum.turkish: 'turkish',
  LanguageEthnicityEnum.swahili: 'swahili',
  LanguageEthnicityEnum.yoruba: 'yoruba',
  LanguageEthnicityEnum.nativeAmerican: 'nativeAmerican',
  LanguageEthnicityEnum.hawaiian: 'hawaiian',
  LanguageEthnicityEnum.vietnamese: 'vietnamese',
  LanguageEthnicityEnum.thai: 'thai',
  LanguageEthnicityEnum.angloSaxon: 'angloSaxon',
  LanguageEthnicityEnum.estonian: 'estonian',
  LanguageEthnicityEnum.finnish: 'finnish',
  LanguageEthnicityEnum.icelandic: 'icelandic',
  LanguageEthnicityEnum.indonesian: 'indonesian',
  LanguageEthnicityEnum.maori: 'maori',
  LanguageEthnicityEnum.mayan: 'mayan',
  LanguageEthnicityEnum.mongolian: 'mongolian',
  LanguageEthnicityEnum.nepalese: 'nepalese',
  LanguageEthnicityEnum.nigerian: 'nigerian',
  LanguageEthnicityEnum.norwegian: 'norwegian',
  LanguageEthnicityEnum.serbian: 'serbian',
  LanguageEthnicityEnum.somali: 'somali',
  LanguageEthnicityEnum.swedish: 'swedish',
  LanguageEthnicityEnum.ukrainian: 'ukrainian',
  LanguageEthnicityEnum.fantasyElvish: 'fantasyElvish',
  LanguageEthnicityEnum.fantasyDwarven: 'fantasyDwarven',
  LanguageEthnicityEnum.fantasyOrcish: 'fantasyOrcish',
  LanguageEthnicityEnum.fantasyGoblin: 'fantasyGoblin',
  LanguageEthnicityEnum.fantasyFae: 'fantasyFae',
  LanguageEthnicityEnum.fantasyAngelic: 'fantasyAngelic',
  LanguageEthnicityEnum.fantasyDemonic: 'fantasyDemonic',
  LanguageEthnicityEnum.fantasyDragon: 'fantasyDragon',
  LanguageEthnicityEnum.fantasyVampire: 'fantasyVampire',
};

const _$MythologyEnumEnumMap = {
  MythologyEnum.greek: 'greek',
  MythologyEnum.norse: 'norse',
  MythologyEnum.roman: 'roman',
  MythologyEnum.celtic: 'celtic',
  MythologyEnum.egyptian: 'egyptian',
  MythologyEnum.hindu: 'hindu',
  MythologyEnum.japanese: 'japanese',
  MythologyEnum.slavic: 'slavic',
  MythologyEnum.mesopotamian: 'mesopotamian',
  MythologyEnum.nativeAmerican: 'nativeAmerican',
  MythologyEnum.lovecraft: 'lovecraft',
};

const _$RaceEnumEnumMap = {
  RaceEnum.human: 'human',
  RaceEnum.elf: 'elf',
  RaceEnum.dwarf: 'dwarf',
  RaceEnum.halfling: 'halfling',
  RaceEnum.orc: 'orc',
  RaceEnum.goblin: 'goblin',
  RaceEnum.vampire: 'vampire',
  RaceEnum.werewolf: 'werewolf',
  RaceEnum.demon: 'demon',
  RaceEnum.angel: 'angel',
  RaceEnum.dragon: 'dragon',
  RaceEnum.fae: 'fae',
  RaceEnum.giant: 'giant',
  RaceEnum.troll: 'troll',
  RaceEnum.lich: 'lich',
  RaceEnum.golem: 'golem',
  RaceEnum.ghost: 'ghost',
  RaceEnum.witch: 'witch',
  RaceEnum.gnome: 'gnome',
  RaceEnum.ogre: 'ogre',
  RaceEnum.hobgoblin: 'hobgoblin',
  RaceEnum.kobold: 'kobold',
  RaceEnum.oni: 'oni',
  RaceEnum.kappa: 'kappa',
  RaceEnum.centaur: 'centaur',
  RaceEnum.satyr: 'satyr',
  RaceEnum.faun: 'faun',
  RaceEnum.minotaur: 'minotaur',
  RaceEnum.harpy: 'harpy',
  RaceEnum.gorgon: 'gorgon',
  RaceEnum.naga: 'naga',
  RaceEnum.cyclops: 'cyclops',
  RaceEnum.ghoul: 'ghoul',
  RaceEnum.wight: 'wight',
  RaceEnum.wraith: 'wraith',
  RaceEnum.spectre: 'spectre',
  RaceEnum.zombie: 'zombie',
  RaceEnum.mummy: 'mummy',
  RaceEnum.draugr: 'draugr',
  RaceEnum.ghast: 'ghast',
  RaceEnum.hag: 'hag',
  RaceEnum.djinn: 'djinn',
  RaceEnum.imp: 'imp',
  RaceEnum.succubus: 'succubus',
  RaceEnum.incubus: 'incubus',
  RaceEnum.mermaid: 'mermaid',
  RaceEnum.merman: 'merman',
  RaceEnum.siren: 'siren',
  RaceEnum.selkie: 'selkie',
  RaceEnum.dryad: 'dryad',
  RaceEnum.nymph: 'nymph',
  RaceEnum.pixie: 'pixie',
  RaceEnum.sprite: 'sprite',
  RaceEnum.sylph: 'sylph',
  RaceEnum.brownie: 'brownie',
  RaceEnum.leprechaun: 'leprechaun',
  RaceEnum.gremlin: 'gremlin',
  RaceEnum.valkyrie: 'valkyrie',
  RaceEnum.warg: 'warg',
  RaceEnum.wendigo: 'wendigo',
  RaceEnum.gargoyle: 'gargoyle',
  RaceEnum.homunculus: 'homunculus',
  RaceEnum.elemental: 'elemental',
  RaceEnum.yeti: 'yeti',
  RaceEnum.sasquatch: 'sasquatch',
  RaceEnum.pegasus: 'pegasus',
  RaceEnum.unicorn: 'unicorn',
  RaceEnum.phoenix: 'phoenix',
  RaceEnum.griffon: 'griffon',
  RaceEnum.hippogriff: 'hippogriff',
  RaceEnum.wyvern: 'wyvern',
  RaceEnum.manticore: 'manticore',
  RaceEnum.sphinx: 'sphinx',
  RaceEnum.thunderbird: 'thunderbird',
  RaceEnum.roc: 'roc',
  RaceEnum.chimera: 'chimera',
  RaceEnum.kraken: 'kraken',
  RaceEnum.hydra: 'hydra',
  RaceEnum.cockatrice: 'cockatrice',
  RaceEnum.bugbear: 'bugbear',
  RaceEnum.chupacabra: 'chupacabra',
  RaceEnum.frostGiant: 'frostGiant',
  RaceEnum.lamassu: 'lamassu',
  RaceEnum.nix: 'nix',
  RaceEnum.poltergeist: 'poltergeist',
};

const _$AgeEnumEnumMap = {
  AgeEnum.child: 'child',
  AgeEnum.youngAdult: 'youngAdult',
  AgeEnum.adult: 'adult',
  AgeEnum.elder: 'elder',
};

const _$EraEnumEnumMap = {
  EraEnum.ancient: 'ancient',
  EraEnum.medieval: 'medieval',
  EraEnum.renaissance: 'renaissance',
  EraEnum.victorian: 'victorian',
  EraEnum.nineteenTwenties: 'nineteenTwenties',
  EraEnum.midcentury: 'midcentury',
  EraEnum.modern: 'modern',
  EraEnum.contemporary: 'contemporary',
  EraEnum.nearFuture: 'nearFuture',
  EraEnum.farFuture: 'farFuture',
  EraEnum.timeless: 'timeless',
};

const _$RoleEnumEnumMap = {
  RoleEnum.hero: 'hero',
  RoleEnum.villain: 'villain',
  RoleEnum.mentor: 'mentor',
  RoleEnum.sidekick: 'sidekick',
  RoleEnum.comicRelief: 'comicRelief',
  RoleEnum.bystander: 'bystander',
  RoleEnum.loveInterest: 'loveInterest',
  RoleEnum.antihero: 'antihero',
  RoleEnum.neutral: 'neutral',
};

const _$CommonnessEnumEnumMap = {
  CommonnessEnum.rare: 'rare',
  CommonnessEnum.uncommon: 'uncommon',
  CommonnessEnum.common: 'common',
};

const _$GenreEnumEnumMap = {
  GenreEnum.fantasy: 'fantasy',
  GenreEnum.sciFi: 'sciFi',
  GenreEnum.cyberpunk: 'cyberpunk',
  GenreEnum.steampunk: 'steampunk',
  GenreEnum.western: 'western',
  GenreEnum.noirDetective: 'noirDetective',
  GenreEnum.horror: 'horror',
  GenreEnum.smut: 'smut',
  GenreEnum.modern: 'modern',
  GenreEnum.historical: 'historical',
  GenreEnum.postApocalyptic: 'postApocalyptic',
};

const _$ThemeEnumEnumMap = {
  ThemeEnum.celestial: 'celestial',
  ThemeEnum.floral: 'floral',
  ThemeEnum.gemstone: 'gemstone',
  ThemeEnum.military: 'military',
  ThemeEnum.literary: 'literary',
  ThemeEnum.regal: 'regal',
  ThemeEnum.fiery: 'fiery',
  ThemeEnum.icy: 'icy',
  ThemeEnum.watery: 'watery',
  ThemeEnum.earthy: 'earthy',
  ThemeEnum.airy: 'airy',
  ThemeEnum.solar: 'solar',
  ThemeEnum.lunar: 'lunar',
  ThemeEnum.nautical: 'nautical',
  ThemeEnum.religious: 'religious',
  ThemeEnum.scholarly: 'scholarly',
  ThemeEnum.rustic: 'rustic',
  ThemeEnum.exotic: 'exotic',
  ThemeEnum.mystical: 'mystical',
  ThemeEnum.brutish: 'brutish',
};
